spring:
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-service:8001
      fail-fast: true
      password: admin
      username: user
