spring:
  application:
    name: deposit-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8001
      fail-fast: true
      password: admin
      username: user
